### ISSUE TITLE
Show Current Location Weather Data on initial load.

### ISSUE THREAD

**Issue by thatfreakcoder** [thatfreakcoder/AngularWeatherApp#1]
When the app is first loaded, it should show the weather information of the current location. Currently no information is being showed

**Comment by amauryverschooren** [comment]
Doing my first work for the hacktoberfest ;-) , studying web development in collage in belgium. 

I can try and give this a shot! (can't promise anything :-) )

**Comment by thatfreakcoder** [comment]
Sure. All the best. Assigning this to you @amauryverschooren

**Comment by amauryverschooren** [comment]
I can't pull anymore data from the weather API. The code does work and loads the current weather at your current location.

should i wait for the api to allow requests again or do i create a PR?

**Comment by thatfreakcoder** [comment]
The API is temporarily blocked due to over usage. It has surpassed the daily request of 60 Requests Per Minuten It will work normally again from tomorrow, hopefully. Or else you can create your own API key with OpenWeatherMap. Just go to api.openweathermap.com and sign up. You can try it with you own api key, if it works, you can make a Pull Request.

**Comment by amauryverschooren** [comment]
Just tried it with my own key and can say that it works perfectly.

PR is already made.

**Comment by thatfreakcoder** [comment]
PR Merged. Do star ⭐ the repo. **#HappyOpenSourcing**.
