### ISSUE TITLE
[ENHANCEMENT] : "Show More" Button is off centered

### ISSUE THREAD

**Issue by thatfreakcoder** [thatfreakcoder/AngularWeatherApp#2]
The **Show More** button is off centered.

**Comment by DeandreJWhite** [comment]
I can take a stab at this one!

**Comment by thatfreakcoder** [comment]
Okay @DeandreJWhite assigning to you.

**Comment by thatfreakcoder** [comment]
@DeandreJWhite Are You working on this or should I remove the assign? Please let me know at the latest.

**Comment by DeandreJWhite** [comment]
I wanted to work on this, and I am great at HTML/CSS... but I cannot figure out how to operate GitHub correctly :/ (How to clone the file and repo?)

If you can help me that’s great, sorry.

**Comment by manuelrhdotcl** [comment]
hi!

i see two PR open, do want to wait for @DeandreJWhite fix?

**Comment by amauryverschooren** [comment]
@manuelrhdotcl I don't know. He's saying he can't figure out how to get it done with Github? I do want to know how he solved it as he is saying that he is good at HTML/CSS ;-)

Maybe @thatfreakcoder need to have a look. greets!

**Comment by DeandreJWhite** [comment]
Hey guys thanks a ton. I am excellent with code but have never used Git before. I am trying to complete a Hacktoberfest challenge but Github is confusing...

Maybe try helping instead of winking at eachother ;-)

**Comment by amauryverschooren** [comment]
We are here to help @DeandreJWhite ,first of all i recommend to download VS code. with this you can easily work on git projects. For the working part here, you first need to fork this project to your own profile. Se the repo we are in now thatfreakcoder/AngularWeatherApp becomes DeandreJWhite/AngularWeatherApp. once you've done that, you need to clone the repo to your pc. you can do this with the git cli, use git bash (i use that) and browse to the folder you want this repo to be in. once there you use the link of this repo in this command `git clone "repo url"`
then the repo wil be "copied" to your folder. Once youve done that you can open the folder with VS Code. Now you can edit the code as you want. Once you're done (and the code works with no errors) you need to:

1. stage the changes
2. commit the changes
3. push the changes
these 3 steps (you can go to the "changes" tab in VS Code to do that) will push the changes you made to the repo in YOUR profile. Once you visit the repo in your profile, it's gonna say at the top '"This repo is x commits ahead of "the repo from thatfreakcoder"'. than you click on "Create pull request" and then if it says that there are no merge conflicts you can create the pull request.

quick guide on how to get this done but the Hacktoberfest have made a video that explains it all.
[Video from Hacktoberfest](https://www.youtube.com/watch?v=jZtECuvNRiw&list=PLseEp7p6EwiZgLPknY4ITJxfoo75wqxph&index=7)

Hope this helps!
Happy coding @DeandreJWhite

**Comment by thatfreakcoder** [comment]
@amauryverschooren gave an excellent explanation @DeandreJWhite . See if that helps, and make a PR. waiting for your PR since it was assigned to you. @DeandreJWhite .

**Comment by amauryverschooren** [comment]
@DeandreJWhite how you doing? if you have any questions, shoot! we're here to help!

Greets Amaury

**Comment by DeandreJWhite** [comment]
Sorry, please remove me from the project.

**Comment by samin-batra** [comment]
Hi @thatfreakcoder , I can work on this. Please assign to me.
