### ISSUE TITLE
[BUG] : More Info table disappears on new city request.

### ISSUE THREAD

**Issue by thatfreakcoder** [thatfreakcoder/AngularWeatherApp#3]
Once the **Show More** Button is clicked, the more info table appears. But it disappears on making a new city request.

**Comment by ielixirz** [comment]
Can I take this ? thanks

**Comment by thatfreakcoder** [comment]
@ielixirz, assigning this one to you. Thank for your interest

**Comment by ielixirz** [comment]
where should I merge the PR to ?

pr opened here 
https://github.com/thatfreakcoder/AngularWeatherApp/pull/7
